modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/lo-fi-modding/no-tools/issues"
[[mods]]
modId="no-tools"
version="${file.jarVersion}"
displayName="No Tools!"
#TODO updateJSONURL="https://myurl.me/"
displayURL="https://github.com/lo-fi-modding/no-tools"
#TODO logoFile="logo.png"
credits="Corey Frenette (Monoxide)"
authors="Corey Frenette"
description='''
Who needs 'em, anyway?
'''
[[dependencies.no-tools]]
  modId="forge"
  mandatory=true
  versionRange="[31.2,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.no-tools]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.15.2]"
  ordering="NONE"
  side="BOTH"
